project_id = "bxinainfibipdxopolpf"

[functions.send-email]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.impersonate-client]
verify_jwt = false

[functions.reset-client-password]
verify_jwt = false